"""Contract tests for the translation layer's falsifier scoring.

The scorer marks the model's own work, so it must be mechanical and it must not flip on
representation. The boundary test exists because the first real falsifier generated by this
module landed exactly on its threshold: the 10-year yield moved from 1.50 to 1.90 against a
0.40 trigger, and binary floating point made that 0.3999999999999999, scoring a refuted call
as standing.
"""

from __future__ import annotations

import pandas as pd
import pytest

from unstructured_momentum.llm import translate as T


def _rec(**kw):
    base = {"as_of": "2019-08-30", "variable": "DGS10", "direction": "rise",
            "threshold": 0.4, "horizon_days": 42, "refutes": "x", "driver": "x",
            "confidence": 5, "vintages": {}}
    return {**base, **kw}


def test_exact_threshold_counts_as_refuted():
    """1.90 minus 1.50 is 0.40 and must clear a 0.40 threshold."""
    r = T.score(_rec())
    assert r["status"] == "refuted", (
        f"exact-threshold move scored {r['status']}; realised {r['realised_move']!r}")


def test_below_threshold_stands():
    assert T.score(_rec(threshold=0.6))["status"] == "stood"


def test_direction_is_respected():
    r = T.score(_rec(direction="fall", threshold=0.25))
    assert r["status"] == "stood"


def test_incomplete_horizon_is_pending_not_scored():
    r = T.score(_rec(as_of="2026-08-18", horizon_days=42))
    assert r["status"] == "pending"


def test_unknown_variable_is_unscoreable():
    r = T.score(_rec(variable="NOT_A_SERIES"))
    assert r["status"] == "unscoreable"


def test_every_registry_series_loads():
    """A falsifier may only name a series the scorer can actually fetch."""
    for name in T.REGISTRY:
        s = T.series(name)
        assert len(s) > 100, f"{name} returned {len(s)} observations"
